#!/bin/bash
set -euo pipefail

echo "--- :shield: Access Policies for Secrets"
echo ""
echo "  Access policies control WHICH builds can access WHICH secrets."
echo "  Defined in YAML — version-controlled, auditable, precise."

echo ""
echo "--- :page_facing_up: Policy Anatomy"
echo ""
echo "  A policy is a set of claims that must ALL match:"
echo ""
echo '    policies:'
echo '      - pipeline_slug: "deploy-*"'
echo '        build_branch: "main"'
echo '        cluster_queue_key: "production"'
echo ""
echo "  This secret is ONLY accessible when:"
echo "    ✅ Pipeline slug matches deploy-*"
echo "    ✅ Branch is main"
echo "    ✅ Running on the production queue"

echo ""
echo "--- :dart: Available Claims"
echo ""
echo "    Claim                  Example                 Type"
echo "    ─────────────────────  ──────────────────────  ──────────"
echo "    pipeline_slug          deploy-production       1st-party"
echo "    build_branch           main, release/*         1st-party"
echo "    build_creator          user-uuid               1st-party"
echo "    cluster_queue_key      production              1st-party"
echo ""
echo "  💡 1st-party claims are generated by Buildkite itself —"
echo "     they can't be spoofed by pipeline YAML or scripts."

echo ""
echo "--- :closed_lock_with_key: First-Party vs Third-Party Claims"
echo ""
echo "  First-party (more secure):"
echo "    Generated by Buildkite, not controllable by pipeline authors."
echo "    e.g., pipeline_slug, build_branch, build_creator"
echo ""
echo "  Third-party:"
echo "    Set by the pipeline YAML or environment hooks."
echo "    Useful but can be modified by anyone with pipeline edit access."

echo ""
echo "--- :bulb: Example: Production Deploy Policy"
echo ""
echo '    # Only the deploy pipeline, on main, by specific users'
echo '    policies:'
echo '      - pipeline_slug: "production-deploy"'
echo '        build_branch: "main"'
echo '        build_creator:'
echo '          - "018f1a2b-..."   # alice'
echo '          - "018f1a2c-..."   # bob'

buildkite-agent annotate --style info --context secrets-policies << 'ANNOTATION'
## :shield: Access Policies — Reference Card

### Example Policy
```yaml
# Secret: PROD_DATABASE_URL
# Only accessible by deploy pipelines on main branch
policies:
  - pipeline_slug: "deploy-*"
    build_branch: "main"
    cluster_queue_key: "production"
```

### Available Claims
| Claim | Type | Description |
|-------|------|-------------|
| `pipeline_slug` | 1st-party | Pipeline that's running |
| `build_branch` | 1st-party | Git branch being built |
| `build_creator` | 1st-party | UUID of user who triggered build |
| `cluster_queue_key` | 1st-party | Queue the job runs on |

> 💡 **1st-party claims** are generated by Buildkite — they can't be spoofed.

### Links
- 📖 [Buildkite Secrets docs](https://buildkite.com/docs/pipelines/security/secrets/buildkite-secrets)
- 📖 [Access Policies docs](https://buildkite.com/docs/pipelines/security/secrets/buildkite-secrets/access-policies)
ANNOTATION

echo ""
echo "✅ Access Policies demo complete"
