#!/bin/bash
set -euo pipefail

echo "+++ :shield: Secrets — Access Policies"
echo ""
echo "  Control WHICH builds can access WHICH secrets. YAML-defined, auditable."
echo ""
echo "  ┌────────────────────────────────────────────────────┐"
echo "  │  policies:                                         │"
echo '  │    - pipeline_slug: "deploy-*"                     │'
echo '  │      build_branch: "main"                          │'
echo '  │      cluster_queue_key: "production"               │'
echo "  └────────────────────────────────────────────────────┘"
echo ""
echo "  Available claims (all 1st-party — can't be spoofed):"
echo ""
echo "  Claim                  Example              "
echo "  ─────────────────────  ─────────────────────"
echo "  pipeline_slug          deploy-production    "
echo "  build_branch           main, release/*      "
echo "  build_creator          user-uuid            "
echo "  cluster_queue_key      production           "
echo ""
echo "  🔐 1st-party = generated by Buildkite, not controllable by pipeline authors"
echo "  📖 docs.buildkite.com/pipelines/security/secrets/buildkite-secrets/access-policies"

buildkite-agent annotate --style info --context secrets-policies << 'ANNOTATION'
## :shield: Access Policies
```yaml
policies:
  - pipeline_slug: "deploy-*"
    build_branch: "main"
    cluster_queue_key: "production"
```
Claims: `pipeline_slug` · `build_branch` · `build_creator` · `cluster_queue_key` (all 1st-party)
- 📖 [Access Policies docs](https://buildkite.com/docs/pipelines/security/secrets/buildkite-secrets/access-policies)
ANNOTATION

echo ""
echo "✅ Access Policies demo complete"
